info:
  app:
    name: Demonstration - Demo App
    description: Demo App
    version: '@project.version@'

#---------------- Config URLs ------------------#
url:
   sample-application: http://localhost:8081

#---------------- Logging ----------------------# 
logging:
  level:
    root: INFO
    sample-application: INFO

#---------------- DataBase ---------------------# 
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://dbdev.crkb0f0v3qft.sa-east-1.rds.amazonaws.com:3306/DBDEV
    username: admin
    password: admin142536
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hikari:
      maximum-pool-size: 1
      pool-name: admin-pool
      connection-timeout: 30000
      maxLifetime: 1200000
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jpa:
    openInView: false
    show_sql: true
    properties:
       hibernate:
          format_sql: false
          enable_lazy_load_no_trans: true
          jdbc.lob.non_contextual_creation: true